<a href="https://colab.research.google.com/github/Siddhesh937/DATASCIENCE/blob/main/MobilePriceRangeclassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Minor project

Problem statement: 
          Create a classification model to predict whether price range of mobile based on certain specification

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sea
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix



In [ ]:
df=pd.read_csv('/content/mobile_price_range_data.csv')
df

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2  ...         20       756  2549     9     7   
1       0.7        136        3  ...        905      1988  2631    17     3   
2       0.9        145        5  ...       1263      1716  2603    11     2   
3       0.8        131        6  ...       1216      1786  2769    16     8   
4       0.6        141        2  ...       1208      1212  1411     8     2   
...     ...        ...      ...  ...        ...       ...   ...   ...   ...   
1995    0.8        106        6  ...       1222      1890   668    13     4   
1996    0.2        187        4  ...        915      1965  2032    11    10   
1997    0.7        108        8  ...        868      1632  3057     9     1   
1998    0.1        145        5  ...        336       670   869    18    10   
1999    0.9        168        6  ...        483       754  3919    19     4   

      talk_time  three_g  touch_screen  wifi  price_range  
0            19        0             0     1            1  
1             7        1             1     0            2  
2             9        1             1     0            2  
3            11        1             0     0            2  
4            15        1             1     0            1  
...         ...      ...           ...   ...          ...  
1995         19        1             1     0            0  
1996         16        1             1     1            2  
1997          5        1             1     0            3  
1998         19        1             1     1            0  
1999          2        1             1     1            3  

[2000 rows x 21 columns]

In [ ]:
df.isnull().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X=df.iloc[:,0:20]
Y=df.iloc[:,20:]

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.25,random_state=1)

# a) Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train.values)

/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
pre=lr.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score
lr1=accuracy_score(y_test,pre)
print(lr1)

0.626


In [ ]:
print('Confusion Matrix')
print(confusion_matrix(y_test,pre))

Confusion Matrix
[[93 21  2  0]
 [24 71 27  4]
 [ 0 35 55 45]
 [ 0  1 28 94]]


In [ ]:
print('Classification Report')
print(classification_report(y_test,pre))

Classification Report
              precision    recall  f1-score   support

           0       0.79      0.80      0.80       116
           1       0.55      0.56      0.56       126
           2       0.49      0.41      0.45       135
           3       0.66      0.76      0.71       123

    accuracy                           0.63       500
   macro avg       0.62      0.63      0.63       500
weighted avg       0.62      0.63      0.62       500



# b) KNN 

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=7)
knn.fit(x_train,y_train)

/usr/local/lib/python3.8/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=7)

In [ ]:
pred1=knn.predict(x_test)

In [ ]:
knn1=accuracy_score(y_test,pred1)
knn1

0.922

In [ ]:
print('Confusion Matrix')
print(confusion_matrix(y_test,pred1))



Confusion Matrix
[[113   3   0   0]
 [  4 116   6   0]
 [  0   9 122   4]
 [  0   0  13 110]]


In [ ]:
print('Classification Report')
print(classification_report(y_test,pred1))

Classification Report
              precision    recall  f1-score   support

           0       0.97      0.97      0.97       116
           1       0.91      0.92      0.91       126
           2       0.87      0.90      0.88       135
           3       0.96      0.89      0.93       123

    accuracy                           0.92       500
   macro avg       0.93      0.92      0.92       500
weighted avg       0.92      0.92      0.92       500



# c) SVM Model

In [ ]:
from sklearn.svm import SVC
s=SVC(kernel='linear')
s.fit(x_train,y_train)

/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='linear')

In [ ]:
pred2=s.predict(x_test)
print(accuracy_score(y_test,pred2))


0.958


In [ ]:
print('Confusion Matrix')
print(confusion_matrix(y_test,pred2))


Confusion Matrix
[[114   2   0   0]
 [  2 121   3   0]
 [  0   8 125   2]
 [  0   0   4 119]]


In [ ]:
print('Classification Report')
print(classification_report(y_test,pred2))

Classification Report
              precision    recall  f1-score   support

           0       0.98      0.98      0.98       116
           1       0.92      0.96      0.94       126
           2       0.95      0.93      0.94       135
           3       0.98      0.97      0.98       123

    accuracy                           0.96       500
   macro avg       0.96      0.96      0.96       500
weighted avg       0.96      0.96      0.96       500



In [ ]:
from sklearn.svm import SVC
s1=SVC(kernel='rbf')
s1.fit(x_train,y_train)


/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

In [ ]:
pred3=s1.predict(x_test)

In [ ]:
print(accuracy_score(y_test,pred3))

0.94


In [ ]:
print('Confusion Matrix')
print(confusion_matrix(y_test,pred3))

Confusion Matrix
[[115   1   0   0]
 [  5 118   3   0]
 [  0   9 120   6]
 [  0   0   6 117]]


In [ ]:
print('Classification Report')
print(classification_report(y_test,pred3))

Classification Report
              precision    recall  f1-score   support

           0       0.96      0.99      0.97       116
           1       0.92      0.94      0.93       126
           2       0.93      0.89      0.91       135
           3       0.95      0.95      0.95       123

    accuracy                           0.94       500
   macro avg       0.94      0.94      0.94       500
weighted avg       0.94      0.94      0.94       500



# d) Decision Tree classifier

In [ ]:
from sklearn.tree import DecisionTreeClassifier
d=DecisionTreeClassifier() 
d.fit(x_train,y_train)


DecisionTreeClassifier()

In [ ]:
pred4=d.predict(x_test)

In [ ]:
print(accuracy_score(y_test,pred4))

0.844


In [ ]:
print('Confusion Matrix')
print(confusion_matrix(y_test,pred4))


Confusion Matrix
[[104  12   0   0]
 [  6 104  16   0]
 [  0  17 101  17]
 [  0   0  10 113]]


In [ ]:
print('Classification Report')
print(classification_report(y_test,pred4))

Classification Report
              precision    recall  f1-score   support

           0       0.95      0.90      0.92       116
           1       0.78      0.83      0.80       126
           2       0.80      0.75      0.77       135
           3       0.87      0.92      0.89       123

    accuracy                           0.84       500
   macro avg       0.85      0.85      0.85       500
weighted avg       0.84      0.84      0.84       500



# e) Random Forest Classifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier
R=RandomForestClassifier()
R.fit(x_train,y_train)


<ipython-input-62-573b6c417d7e>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  R.fit(x_train,y_train)


RandomForestClassifier()

In [ ]:
pred5=R.predict(x_test)

In [ ]:
print(accuracy_score(y_test,pred5))

0.842


In [ ]:
print('Confusion Matrix')
print(confusion_matrix(y_test,pred5))

Confusion Matrix
[[108   8   0   0]
 [ 13  95  18   0]
 [  0  17 110   8]
 [  0   0  15 108]]


In [ ]:
print('Classification Report')
print(classification_report(y_test,pred5))

Classification Report
              precision    recall  f1-score   support

           0       0.89      0.93      0.91       116
           1       0.79      0.75      0.77       126
           2       0.77      0.81      0.79       135
           3       0.93      0.88      0.90       123

    accuracy                           0.84       500
   macro avg       0.85      0.84      0.84       500
weighted avg       0.84      0.84      0.84       500

